#!/bin/bash

# Update the system
sudo apt update
sudo apt upgrade -y

# Install Nginx
sudo apt install nginx -y

# Configure custom HTTP response header
sudo bash -c 'echo "add_header X-Served-By $HOSTNAME;" > /etc/nginx/conf.d/custom_header.conf'

# Restart Nginx
sudo systemctl restart nginx

